export const projects = [
    {
      id: 1,
      name: 'Project 1',
      location: 'Nairobi',
      image: require('../images/5.png'),
      about: 'Description about Project 1.',
      challenges: 'Challenges faced by Project 1.',
      achievements: 'Achievements of Project 1.',
      partners: 'Partners involved in Project 1.',     
    },
    {
      id: 2,
      name: 'Project 2',
      location: 'Thika',
      image: require('../images/1.jpg'),
      about: 'Description about Project 2.',
      challenges: 'Challenges faced by Project 2.',
      achievements: 'Achievements of Project 2.',
      partners: 'Partners involved in Project 2.',      
    },
    {
      id: 3,
      name: 'Project 3',
      location: 'Nakuru',
      image: require('../images/6.png'),
      details: {
      about: 'Description about Project 3.',
      challenges: 'Challenges faced by Project 3.',
      achievements: 'Achievements of Project 3.',
      partners: 'Partners involved in Project 3.',
      },
    },
    {
      id: 4,
      name: 'Project 4',
      location: 'Kisumu',
      image: require('../images/2.jpg'),
      about: 'Description about Project 4.',
      challenges: 'Challenges faced by Project 4.',
      achievements: 'Achievements of Project 4.',
      partners: 'Partners involved in Project 4.',
    },
    {
      id: 5,
      name: 'Project 5',
      location: 'Mombasa',
      image: require('../images/5.png'),
      about: 'Description about Project 5.',
      challenges: 'Challenges faced by Project 5.',
      achievements: 'Achievements of Project 5.',
      partners: 'Partners involved in Project 5.',
    },
    {
      id: 6,
      name: 'Project 6',
      location: 'Ruiru',
      image: require('../images/6.png'),
      about: 'Description about Project 6.',
      challenges: 'Challenges faced by Project 6.',
      achievements: 'Achievements of Project 6.',
      partners: 'Partners involved in Project 6.',
    },
  ];
  